# dependency for product service:

version: '3.9'
services:
  product-service:
    ports:
      - "8080:8080"
    build:
      context: ./product-service
      dockerfile: Dockerfile
    image: product-service:1.0
    container_name: product-service
    depends_on:
      - mongodb
    networks:
      - spring
    environment:
      SPRING_PROFILES_ACTIVE: docker

  mongodb:
    ports:
      - "27017:27017"
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootadmin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./data/mongo/coursework:/data/db
      - ./init/mongo/docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: unless-stopped
    command: mongod --auth
    networks:
      - spring

  mongodb-express:
    ports:
      - "8081:8081"
    image: mongo-express
    container_name: mongo-express-1
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootadmin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    restart: unless-stopped
    depends_on:
      - mongodb
    networks:
      - spring

networks:
  spring:
    driver: bridge